name: 'Deploy'
on:
  workflow_dispatch:

permissions:
  id-token: write # OIDC
  contents: read # action checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: https://www.molotov.tv
    steps:
      - name: my first step
        run: echo "Hello world!"

      - name: print variables
        run: |
          echo "my region: ${{ vars.AWS_REGION }}"

      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4

      - name: 👏 Build
        run: |
          npm install
          npm run build
